name: Feature request
description: Propose a feature or improvement
body:
  - type: textarea
    id: need
    attributes:
      label: What application problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior and alternatives
    validations:
      required: true
  - type: textarea
    id: failures
    attributes:
      label: Tradeoffs and testing
